### ISSUE TITLE
PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by nualamo** [Satyam/react-simple-idle-monitor#2]
With the latest version of React it is no longer possible to get PropTypes via the main React package
`import React, { Component, PropTypes } from 'react';`

It causes Deprecation warning on React:
**Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.**

React recommends to use prop-types npm package: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by Satyam** [comment]
Done.  

see: https://github.com/Satyam/react-simple-idle-monitor/commit/4a7f4d87252247f7025ddacbdece0bc05cb9ea90

I bumped the package version to 0.2.0

Thanks for reporting it.

**Comment by nualamo** [comment]
Many thanks for updating this so quickly. Much appreciated.
