### ISSUE TITLE
React should be a peer dependency

### ISSUE THREAD

**Issue by scottc-netflix** [Satyam/react-simple-idle-monitor#4]
I'm on React 16 and Webpack is also importing React 15 because React isn't declared as a peer dependency instead of a regular dependency in react-simple-idle-monitor.

**Comment by Satyam** [comment]
I have just updated all the dependencies, including React to their latest version as of today. 
I also moved react and prop-types to peerDependencies.
Hoping it works, I'm closing this issue, please re-open it if it doesn't.
